version: "3.3"
services:
   db:
      image: mysql:5.7
      restart: always
      ports:
         - "3306:3306"
      environment:
         MYSQL_DATABASE: "webformat-crm"
         MYSQL_ROOT_PASSWORD: "password"
      volumes:
         - db-data:/var/lib/mysql
volumes:
   db-data: {}
